// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdEy44fbdhZ6PG33oOaSgxMWomsdSig-0',
    appId: '1:23862615094:web:6f43bd1160ed42a0a90c97',
    messagingSenderId: '23862615094',
    projectId: 'solopreneur-6f649',
    authDomain: 'solopreneur-6f649.firebaseapp.com',
    storageBucket: 'solopreneur-6f649.appspot.com',
    measurementId: 'G-J7XH9G2PHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTRWmiqByGYWQcN7-REirVQJnQmiOfIk0',
    appId: '1:23862615094:android:ccbf9845276928aba90c97',
    messagingSenderId: '23862615094',
    projectId: 'solopreneur-6f649',
    storageBucket: 'solopreneur-6f649.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT1CnWumGgzs24GympbJI8UqV7W1cWTFs',
    appId: '1:23862615094:ios:a477862235dfc37ca90c97',
    messagingSenderId: '23862615094',
    projectId: 'solopreneur-6f649',
    storageBucket: 'solopreneur-6f649.appspot.com',
    iosBundleId: 'com.example.solopreneuer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT1CnWumGgzs24GympbJI8UqV7W1cWTFs',
    appId: '1:23862615094:ios:50c9957d04b36fe1a90c97',
    messagingSenderId: '23862615094',
    projectId: 'solopreneur-6f649',
    storageBucket: 'solopreneur-6f649.appspot.com',
    iosBundleId: 'com.example.solopreneuer.RunnerTests',
  );
}
